from pydantic import BaseModel
class MushroomBody(BaseModel):
    capShape: str
    capSurface: str
    capColor: str
    bruises: str
    odor: str
    gillAttachment: str
    gillSpacing: str
    gillSize: str
    gillColor: str
    stalkShape: str
    stalkRoot: str
    stalkSurfaceAboveRing: str
    stalkSurfaceBelowRing: str
    stalkColorAboveRing: str
    stalkColorBelowRing: str
    veilType: str
    veilColor: str
    ringNumber: str
    ringType: str
    sporePrintColor: str
    population: str
    habitat: str
